### ISSUE TITLE
this library does not seem to work with jetty 9.4.7

### ISSUE THREAD

**Issue by vkurland** [codeminders/socket.io-server-java#5]
I get the following exception when I try:

`2017-09-08 16:48:36,797 ERROR main                                     [.z.s.NIOServerCnxnFactory]: Thread Thread[main,5,main] died
java.lang.NoSuchMethodError: org.eclipse.jetty.websocket.server.WebSocketServerFactory: method <init>()V not found
	at com.codeminders.socketio.server.transport.jetty.JettyWebSocketTransport.<init>(JettyWebSocketTransport.java:51)
	at com.codeminders.socketio.server.transport.jetty.JettyTransportProvider.createWebSocketTransport(JettyTransportProvider.java:37)
	at com.codeminders.socketio.server.transport.AbstractTransportProvider.init(AbstractTransportProvider.java:31)
	at com.codeminders.socketio.server.transport.jetty.JettySocketIOServlet.init(JettySocketIOServlet.java:42)
	at net.happygears.nw2.socket_io.SIOBackendServlet.init(SIOBackendServlet.java:24)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:637)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:421)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:348)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:453)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:420)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at net.happygears.nw2.WebServer.start(WebServer.java:1288)
	at net.happygears.nw2.netspyglass.NetSpyGlass.startWebServer(NetSpyGlass.java:248)
	at net.happygears.nw2.Nw2UI.run(Nw2UI.java:332)
	at net.happygears.nw2.ViewsTester.run(ViewsTester.java:23)
	at net.happygears.nw2.Nw2ViewsTester.main(Nw2ViewsTester.java:28)`

**Comment by alexsaveliev** [comment]
@vkurland please switch to updated version `com.codeminders.socketio:socket-io:1.0.3` we have released yesterday. I have tried chat demo with Jetty 9.4.7 RC0 and it works fine

**Comment by vkurland** [comment]
It looks like your API has changed. I used to use your class JettySocketIOServlet but I can't find it anymore. How do I build a servlet to handle Socket-IO connections? In my application, I need this to be a part of existing web server that has lots of other servlets and serves everything on the same port

**Comment by alexsaveliev** [comment]
Please use `com.codeminders.socketio.server.transport.websocket.WebsocketIOServlet` instead of former 
`JettySocketIOServlet`

for example,

```java
public class ChatSocketServlet extends WebsocketIOServlet {
....
    public void init(ServletConfig config) throws ServletException {
        super.init(config);
        of("/foo").on(new ConnectionListener() {
            @Override
            public void onConnect(final Socket socket) {
                socket.on("bar", new EventListener() {
                    @Override
                    public Object onEvent(String name, Object[] args, boolean ackRequested) {
                        return "OK";
                    }
                });
                .....
            }
        }
    }
.....
}
```

You can also catch me on Skype to discuss things, I would be happy to help

**Comment by vkurland** [comment]
this helps, I was able to move onto the next step. Unfortunately, this wasn't enough. 

> Caused by: java.lang.NoSuchFieldError: WRITE_DURATIONS_AS_TIMESTAMPS
> 	at com.fasterxml.jackson.datatype.joda.ser.DurationSerializer.<init>(DurationSerializer.java:28)
> 	at com.fasterxml.jackson.datatype.joda.ser.DurationSerializer.<init>(DurationSerializer.java:25)
> 	at com.fasterxml.jackson.datatype.joda.JodaModule.<init>(JodaModule.java:43)
> 	at net.happygears.nw2.json.JsonObjectMapperFactory.actuallyCreateMapper(JsonObjectMapperFactory.java:71)
> 	at net.happygears.nw2.json.JsonObjectMapperFactory.createMapper(JsonObjectMapperFactory.java:52)
> 	at net.happygears.nw2.db.hbm.AreaModel.<clinit>(AreaModel.java:32)
> 	at java.lang.Class.forName0(Native Method)

this has nothing to do with Socket-io but as far as I understand, this error is caused by incompatible versions of jackson-databind and jackson-datatype-joda.

Looks like your library depends on jackson-databind v2.4.0 which is a bit too old and it causes compatibility issues with my code that depends on a newer version. 

Is there a particular reason you need the old one?  I believe anything newer than 2.5.0 should work for me but as fyi, my pom.xml declares dependency on jackson-core 2.9.0.pr3

pom that comes with your library declares this:

>     <dependencies>
>         <dependency>
>             <groupId>com.fasterxml.jackson.core</groupId>
>             <artifactId>jackson-core</artifactId>
>             <version>2.4.0</version>
>         </dependency>
>         <dependency>
>             <groupId>com.fasterxml.jackson.core</groupId>
>             <artifactId>jackson-databind</artifactId>
>             <version>2.4.0</version>
>         </dependency>
>         <dependency>
>             <groupId>javax.websocket</groupId>
>             <artifactId>javax.websocket-api</artifactId>
>             <version>1.1</version>
>             <scope>provided</scope>
>         </dependency>
>     </dependencies>

**Comment by alexsaveliev** [comment]
bumped dependency versions to the latest ones:
- Guava 23.0
- Jackson 2.9.1

Please try with snapshot version built from source code

**Comment by vkurland** [comment]
I have worked around this issue by excluding transient dependencies:

>         <dependency>
>             <groupId>com.codeminders.socketio</groupId>
>             <artifactId>socket-io</artifactId>
>             <version>1.0.3</version>
>             <exclusions>
>                 <exclusion>
>                     <groupId>com.fasterxml.jackson.core</groupId>
>                     <artifactId>jackson-core</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>com.fasterxml.jackson.core</groupId>
>                     <artifactId>jackson-databind</artifactId>
>                 </exclusion>
>             </exclusions>
>         </dependency>
> 

looks like your server works for me now, thank you
